### ISSUE TITLE
Support for Neo4j 2.2+ authentication

### ISSUE THREAD

**Issue by gsummer** [cyNeo4j/cyNeo4j#10]
By default Neo4j 2.2+ will have authentication ENABLED!
cyNeo4j can not deal with this yet!

**Comment by dhimmel** [comment]
+1, perhaps authentication information could be provided in the URI, like [py2neo](http://py2neo.org/2.0/essentials.html) allows:

```
http://user:password@localhost:7474/db/data/
```

**Comment by gsummer** [comment]
True, thanks for the tip. That would be a quick workaround. I call it
workaround because part of the intended audience might not be familiar with
this way of representing username + password. I'll have to integrate a good
old username + password element in the UI.

**Comment by nachoferre** [comment]
any news???

**Comment by gsummer** [comment]
Basic auth is in.
Arrays are better supported.

For a release on the app store I still want to put in some quality of life
improvements. This should tide you over though.

https://github.com/gsummer/cyNeo4j/releases/tag/v1.3dev

**Comment by DeniseSl22** [comment]
Bumped to Neo4j 3.5.7.
