### ISSUE TITLE
Cypher queries

### ISSUE THREAD

**Issue by Balgorinfo** [cyNeo4j/cyNeo4j#11]
Thanks for a super app! If possible, it would be really super if a) the standard cypher query would be taken out of the code of the app and instead put into a txt-file that would be referenced by the app (thus making it change-able), b) if such an external file could hold several "standard" cypher queries, and c) if it would be possible to refer to the property of a selected object in cytoscape in the cypher query (such as ?.id being the id property of the selected node)
Kind regards

**Comment by DeniseSl22** [comment]
@Balgorinfo : the CYHPER queries build-up are highly dependant on the knowledge in the database (besides very basic queries like MATCH (n) RETURN n LIMIT 25 ). We are however expanding the functionalities of this app with specific metabolomics queries. I will close this issue to create some more detailed ones.
