### ISSUE TITLE
neo4j 3.x plans?

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [cyNeo4j/cyNeo4j#16]
Are there plans to support this plugin for neo4j 3.x?

I've tried installing the necessary extensions in neo4j 3.x, so that I can use cyNeo4j, but the neo4j extensions just produce stack traces and the cystoscape plugin doesn't seem to do anything.

If there is still active interested & development on this project, I'll add the stack traces.

**Comment by AustEcon** [comment]
I am wanting to use Neo4j with Cytoscape... any progress on this front??
- What are my best options for open source vizualisation software for neo4j (I use python mainly)...
- But I really want to use Cytoscape if it can be a good solution because I'm into biomedical area...

**Comment by DeniseSl22** [comment]
@SolomonShorser-OICR and @AustEcon : thank you for your questions; we are in the process of updating the cyNeo4j app to work with neo4j 3.x (and later with 4.x). The source code in this repo should now compile a properly working version tested with Cytoscape 3.9.1 and Neo4j 3.5.7 (community edition).
