### ISSUE TITLE
Allow setting a different port than 7474

### ISSUE THREAD

**Issue by ghuls** [cyNeo4j/cyNeo4j#6]
I tried to connect to my test neo4j instance (via the "Connect to Instance" submenu), which is running at:

```
http://localhost:7484
```

instead of:

```
http://localhost:7474
```

But I am unable to select the "OK" button, when I change the **http://localhost:7474** to something else. It would be nice if this was possible (eventually with a warning if you are trying to connect to a non-default port (not 7474) of a neo4j server.

**Comment by DeniseSl22** [comment]
Closing issue, seems to be resolved.
