### ISSUE TITLE
Support for Neo4j 2.2.0-M04

### ISSUE THREAD

**Issue by pasculorente** [cyNeo4j/cyNeo4j#9]
Are you planning to support last Neo4j release? Button 'OK' when connecting is dummy (I think and exception is running) although server is up and status is good.

**Comment by gsummer** [comment]
There are actually 2 issues:
the connect issue is that neo4j 2.2+ has an authentication active by default now. CyNeo4j can not deal with this yet. Temporarily you can deactivate this authentication in the $NEO4J_HOME/conf/neo4j-server.properties [dbms.security.auth_enabled=false]. I'll get on it asap.

The second issue is that the plugins for neo4j are not build against neo4j 2.2 yet. This seems to create some issues but I need to investigate this further.

**Comment by cuscu** [comment]
Thank you. I disabled the authentication and it worked!!

**Comment by DeniseSl22** [comment]
Bumped to Neo4j 3.5.7.
